### ISSUE TITLE
Pool should call psycopg2.connect not psycopg2._connect

### ISSUE THREAD

**Issue by mjgp2** [Changaco/psycopg2-pool#2]
Currently the pool calls the private method `psycopg2._connect` rather than the public method `psycopg2.connect`. This breaks tooling such as AWS XRay that wraps the public method.

**Comment by Changaco** [comment]
Feel free to open a pull request.

I don't remember why I chose to call the “private” method. It could have been a micro-optimization, or there might have been a more important reason.

**Comment by mjgp2** [comment]
Opened PR: https://github.com/Changaco/psycopg2-pool/pull/3

**Comment by mjgp2** [comment]
Thanks for merging @Changaco ! Any chance you can do a release? :)

**Comment by Changaco** [comment]
Done.
